services:
  postgres:
    container_name: postgres
    image: postgres:17.5-alpine3.22
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  api:
    container_name: api
    image: alvesluis0/catalog-management-api:master
    ports:
      - "3000:3000"
    env_file: .env