services:
  postgres:
    container_name: postgres
    image: postgres:17.5-alpine3.22
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  redis:
    container_name: redis
    image: redis:8.0.3-alpine3.21
    ports:
      - "6379:6379"

  sidekiq:
    container_name: sidekiq
    image: alvesluis0/catalog-management-api:develop
    env_file: .env
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis

  api:
    container_name: api
    image: alvesluis0/catalog-management-api:develop
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - sidekiq